export const textTask = [
    `
# 日常業務
## 掃除
- カウンター
    - [x] から拭き
        - Aさん実施
    - [ ] 水拭き
        - Bさん実施予定
        - 少し時間かかる予定
- キッチン
    - [ ] スプレー
    - [ ] 拭き上げ
- タイトルlv1
    - タイトルlv1.コメント
    - [ ] タイトルlv1.タスク(1)
    - タイトルlv2
        - [ ] タイトルlv2.タスク(1)
        - [ ] タイトルlv2.タスク(2)
        - タイトルlv3
            - タイトルlv3.コメント(1)
            - [ ] タイトルlv3.タスク
            - タイトルlv3.コメント(2)
    - [ ] タイトルlv1.タスク(1)
`,
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
    "| Option | Description |",
    "| ------ | ----------- |",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "Right aligned columns",
    "",
    "| Option | Description |",
    "| ------:| -----------:|",
    "| data   | path to data files to supply the data that will be passed into templates. |",
    "| engine | engine to be used for processing templates. Handlebars is the default. |",
    "| ext    | extension to be used for dest files. |",
    "",
    "",
    "",
].join("\n")
